/*
 * gen_testdata - Generate a synthetic climate netCDF file for testing ked.
 *
 * Creates a netCDF-4 file with:
 *   Dimensions: time(12, unlimited), lat(36), lon(72)
 *   Variables:  time, lat, lon, temperature, precipitation
 *   Global attributes: title, institution, history, Conventions
 */
#include <netcdf.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>

#define NLAT  36
#define NLON  72
#define NTIME 12

#define NC_CHECK(call) do { \
    int _rc = (call); \
    if (_rc != NC_NOERR) { \
        fprintf(stderr, "NetCDF error at %s:%d: %s\n", \
                __FILE__, __LINE__, nc_strerror(_rc)); \
        exit(1); \
    } \
} while(0)

int main(int argc, char **argv)
{
    const char *outpath = "test_climate.nc";
    if (argc > 1) outpath = argv[1];

    int ncid, time_dim, lat_dim, lon_dim;
    int time_var, lat_var, lon_var, temp_var, precip_var;

    /* Create netCDF-4 file */
    NC_CHECK(nc_create(outpath, NC_NETCDF4 | NC_CLOBBER, &ncid));

    /* Define dimensions */
    NC_CHECK(nc_def_dim(ncid, "time", NC_UNLIMITED, &time_dim));
    NC_CHECK(nc_def_dim(ncid, "lat", NLAT, &lat_dim));
    NC_CHECK(nc_def_dim(ncid, "lon", NLON, &lon_dim));

    /* Define coordinate variables */
    NC_CHECK(nc_def_var(ncid, "time", NC_DOUBLE, 1, &time_dim, &time_var));
    NC_CHECK(nc_def_var(ncid, "lat", NC_DOUBLE, 1, &lat_dim, &lat_var));
    NC_CHECK(nc_def_var(ncid, "lon", NC_DOUBLE, 1, &lon_dim, &lon_var));

    /* Define data variables */
    int dims3d[] = {time_dim, lat_dim, lon_dim};
    NC_CHECK(nc_def_var(ncid, "temperature", NC_FLOAT, 3, dims3d, &temp_var));
    NC_CHECK(nc_def_var(ncid, "precipitation", NC_FLOAT, 3, dims3d, &precip_var));

    /* Variable attributes */
    NC_CHECK(nc_put_att_text(ncid, time_var, "units",
             strlen("days since 2000-01-01"), "days since 2000-01-01"));
    NC_CHECK(nc_put_att_text(ncid, time_var, "calendar",
             strlen("standard"), "standard"));
    NC_CHECK(nc_put_att_text(ncid, time_var, "axis",
             strlen("T"), "T"));

    NC_CHECK(nc_put_att_text(ncid, lat_var, "units",
             strlen("degrees_north"), "degrees_north"));
    NC_CHECK(nc_put_att_text(ncid, lat_var, "axis",
             strlen("Y"), "Y"));
    NC_CHECK(nc_put_att_text(ncid, lat_var, "long_name",
             strlen("latitude"), "latitude"));

    NC_CHECK(nc_put_att_text(ncid, lon_var, "units",
             strlen("degrees_east"), "degrees_east"));
    NC_CHECK(nc_put_att_text(ncid, lon_var, "axis",
             strlen("X"), "X"));
    NC_CHECK(nc_put_att_text(ncid, lon_var, "long_name",
             strlen("longitude"), "longitude"));

    NC_CHECK(nc_put_att_text(ncid, temp_var, "units",
             strlen("K"), "K"));
    NC_CHECK(nc_put_att_text(ncid, temp_var, "long_name",
             strlen("Near-Surface Air Temperature"),
             "Near-Surface Air Temperature"));
    float fill_val = -9999.0f;
    NC_CHECK(nc_put_att_float(ncid, temp_var, "_FillValue",
             NC_FLOAT, 1, &fill_val));

    NC_CHECK(nc_put_att_text(ncid, precip_var, "units",
             strlen("kg m-2 s-1"), "kg m-2 s-1"));
    NC_CHECK(nc_put_att_text(ncid, precip_var, "long_name",
             strlen("Precipitation"), "Precipitation"));
    NC_CHECK(nc_put_att_float(ncid, precip_var, "_FillValue",
             NC_FLOAT, 1, &fill_val));

    /* Global attributes */
    NC_CHECK(nc_put_att_text(ncid, NC_GLOBAL, "title",
             strlen("Synthetic Climate Test Data"),
             "Synthetic Climate Test Data"));
    NC_CHECK(nc_put_att_text(ncid, NC_GLOBAL, "institution",
             strlen("ked test suite"), "ked test suite"));
    NC_CHECK(nc_put_att_text(ncid, NC_GLOBAL, "Conventions",
             strlen("CF-1.8"), "CF-1.8"));

    char history[256];
    time_t now = time(NULL);
    struct tm *tm_now = gmtime(&now);
    snprintf(history, sizeof(history), "%04d-%02d-%02d: generated by gen_testdata",
             tm_now->tm_year + 1900, tm_now->tm_mon + 1, tm_now->tm_mday);
    NC_CHECK(nc_put_att_text(ncid, NC_GLOBAL, "history",
             strlen(history), history));

    NC_CHECK(nc_enddef(ncid));

    /* Write coordinate data */
    double time_vals[NTIME];
    for (int t = 0; t < NTIME; t++) {
        time_vals[t] = (double)(t * 30);  /* ~monthly */
    }
    NC_CHECK(nc_put_var_double(ncid, time_var, time_vals));

    double lat_vals[NLAT];
    for (int j = 0; j < NLAT; j++) {
        lat_vals[j] = -87.5 + (double)j * 5.0;
    }
    NC_CHECK(nc_put_var_double(ncid, lat_var, lat_vals));

    double lon_vals[NLON];
    for (int i = 0; i < NLON; i++) {
        lon_vals[i] = 2.5 + (double)i * 5.0;
    }
    NC_CHECK(nc_put_var_double(ncid, lon_var, lon_vals));

    /* Write data variables with realistic-ish values */
    float *data = malloc((size_t)NLAT * (size_t)NLON * sizeof(float));
    if (!data) { fprintf(stderr, "out of memory\n"); return 1; }

    for (int t = 0; t < NTIME; t++) {
        /* Temperature: ~220-310K, varies with latitude and season */
        for (int j = 0; j < NLAT; j++) {
            for (int i = 0; i < NLON; i++) {
                double lat = lat_vals[j];
                double seasonal = 10.0 * cos(2.0 * M_PI * (double)t / 12.0);
                data[j * NLON + i] = (float)(280.0
                    - 40.0 * fabs(lat) / 90.0
                    + seasonal * (lat > 0 ? 1.0 : -1.0)
                    + 2.0 * sin((double)i * 0.5));
            }
        }
        size_t start[] = {(size_t)t, 0, 0};
        size_t count[] = {1, NLAT, NLON};
        NC_CHECK(nc_put_vara_float(ncid, temp_var, start, count, data));

        /* Precipitation: 0-1e-4 kg/m2/s, tropical peak */
        for (int j = 0; j < NLAT; j++) {
            for (int i = 0; i < NLON; i++) {
                double lat = lat_vals[j];
                double tropical = exp(-lat * lat / 800.0);
                data[j * NLON + i] = (float)(5e-5 * tropical
                    * (1.0 + 0.3 * sin((double)i * 0.3 + (double)t)));
            }
        }
        NC_CHECK(nc_put_vara_float(ncid, precip_var, start, count, data));
    }

    free(data);
    NC_CHECK(nc_close(ncid));

    printf("Created %s (%d times, %dx%d grid, 2 variables)\n",
           outpath, NTIME, NLAT, NLON);
    return 0;
}
